baseURL = "https://serverlessdays.amsterdam/"
languageCode = "en-us"
title = "ServerlessDays Amsterdam"

[params]
    logo = "/images/logo_serverless_amsterdam.svg"
    description = "A community based conference focusing on Serverless based platforms and technologies. Amsterdam, May 8, 2020"
    mascot = "/images/UnicornDutchified.png"
    date = "May 8, 2020"
    city = "Amsterdam"
    twitter = "ServerlessDAms"
    email = "amsterdam@serverlessdays.io"
    backgroundImage = "https://res.cloudinary.com/serverlessdays/image/upload/c_scale,q_auto:best,w_1920/v1527152567/amsterdam-2018.jpg"
    prospectus = "https://serverlessdays.amsterdam/ServerlessDaysAms_SponsorProspectus_2020.pdf"

[[params.dates]]
    date = "January 10, 2020"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "February 23, 2020"
    text = "CFP Closes"
    done = true

[[params.dates]]
    date = "February 25, 2020"
    text = "Tickets go on Sale"
    done = true

[[params.dates]]
    date = "April 4, 2020"
    text = "Speaker Announcement"
    done = true

[params.venue]
    name = "online"
    link = "https://discord.gg/d88jSxC"
    text = "We will be streaming the event as well as having a lively discussion on our discord server"

[[params.sponsors.gold]]
    name = "Container Solutions"
    link = "https://www.container-solutions.com/"
    logo = "./images/sponsors/ContainerSolutionsArtboard.svg"
    width = 400

[[params.sponsors.silver]]
    name = "Microsoft"
    link = "https://www.microsoft.com"
    logo = "./images/sponsors/Microsoft_logo.svg"
    width = 250

[[params.sponsors.silver]]
    name = "Xpirit"
    link = "https://xpirit.com/"
    logo = "./images/sponsors/xpiritlogo_rgb_outlines.svg"
    width = 250

[[params.sponsors.community]]
    name = "Thundra"
    link = "https://www.thundra.io/"
    logo = "./images/sponsors/Thundra-main-blue.svg"
    width = 220

[[params.sponsors.raffle]]
    name = "JetBrains"
    link = "https://www.jetbrains.com/"
    logo = "./images/sponsors/jetbrains-variant-4.svg"
    width = 170

[[params.sponsors.raffle]]
    name = "O'Reilly"
    link = "https://www.oreilly.com/"
    logo = "./images/sponsors/oreilly_logo_mark_red.svg"
    width = 170

[params.tickets]
    titolink = "https://ti.to/serverlessdaysams/2020"
    price = "60 EUR"

[[params.agenda]]
    time = "9:00 - 9:10"
    type = "coffee"
    title = "Opening Remarks"
[[params.agenda]]
    time = "9:10 - 9:45"
    type = "keynote"
    talk = "ant-stanley"
[[params.agenda]]
    time = "9:50 - 10:25"
    type = "talk"
    talk = "tomasz-konieczny"
[[params.agenda]]
    time = "10:25 - 10:35"
    type = "coffee"
    title = "Break"
[[params.agenda]]
    time = "10:35 - 11:10"
    type = "talk"
    talk = "riccardo-mocchetti"
[[params.agenda]]
    time = "11:15 - 11:45"
    type = "talk"
    talk = "aymen-chetoui"
[[params.agenda]]
    time = "11:50 - 12:00"
    type = "coffee"
    title = "Break"
[[params.agenda]]
    time = "12:00 - 12:10"
    type = "lightning"
    talk = "ebru-cucen"
[[params.agenda]]
    time = "12:15 - 12:40"
    type = "panel"
    talk = "experts-panel"
[[params.agenda]]
    time = "12:40 - 13:20"
    type = "coffee"
    title = "Lunch Break"
[[params.agenda]]
    time = "13:20 - 13:55"
    type = "talk"
    talk = "sven-al-hamad"
[[params.agenda]]
    time = "14:00 - 14:35"
    type = "talk"
    talk = "josh-carlisle"
[[params.agenda]]
    time = "14:35 - 14:45"
    type = "coffee"
    title = "Break"
[[params.agenda]]
    time = "14:45 - 15:20"
    type = "talk"
    talk = "kayz-shimizu"
[[params.agenda]]
    time = "15:25 - 16:00"
    type = "talk"
    talk = "sia-ghassemi"
[[params.agenda]]
    time = "16:00 - 16:10"
    type = "coffee"
    title = "Break"
[[params.agenda]]
    time = "16:10 - 16:20"
    type = "lightning"
    talk = "sebastien-goasguen"
[[params.agenda]]
    time = "16:25 - 16:50"
    type = "panel"
    talk = "experts-panel"
[[params.agenda]]
    time = "16:55 - 17:30"
    type = "keynote"
    talk = "simona-cotin"
[[params.agenda]]
    time = "17:35 - 17:50"
    type = "coffee"
    talk = "Raffle & Closing Remarks"
[[params.agenda]]
    time = "17:50 - open end"
    type = "afterparty"
    talk = "Afterparty"