baseURL = "https://serverlessdays.amsterdam/"
languageCode = "en-us"
title = "ServerlessDays Amsterdam"

[params]
    logo = "/images/logo_serverless_amsterdam.svg"
    description = "A community based conference focusing on Serverless based platforms and technologies. Amsterdam, March 29, 2019"
    mascot = "/images/UnicornDutchified.png"
    date = "May 8, 2020"
    city = "Amsterdam"
    twitter = "ServerlessDAms"
    email = "amsterdam@serverlessdays.io"
    backgroundImage = "https://res.cloudinary.com/serverlessdays/image/upload/c_scale,q_auto:best,w_1920/v1527152567/amsterdam-2018.jpg"
    prospectus = "https://serverlessdays.amsterdam/2020_serverlessdays_nl_prospectus.pdf"

[[params.dates]]
    date = "December 16, 2019"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "TODO"
    text = "CFP Closes"

[[params.dates]]
    date = "TODO"
    text = "Tickets go on Sale"

[[params.dates]]
    date = "TODO"
    text = "Schedule Announcement"

[params.venue]
    name = "Pakhuis de Zwijger"
    link = "https://dezwijger.nl/"
    map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2435.6456449004804!2d4.919928715875416!3d52.37684507978742!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c609a80e2c8a2f%3A0x2d9e404fc8f71f8d!2sPakhuis+de+Zwijger!5e0!3m2!1sru!2snl!4v1550737160263"
    text = "The venue Pakhuis de Zwijger provides a state-of-the-art AV system and catering, as well as a beautiful view of Amsterdam."

