baseURL = "https://www.serverlessdays.me/"
languageCode = "en-au"
title = "ServerlessDays Melbourne"

[params]
    logo = "/images/serverless_logo_melb.png"
    description = "A community based conference focusing on Serverless based platforms and technologies. Melbourne, August 29, 2019"
    mascot = "/images/octo_mascot.png"
    date = "August 29, 2019"
    city = "Melbourne"
    twitter = "ServerlessMEL"
    email = "melbourne@serverlessdays.io"
    backgroundImage = "/images/melbourne2.jpg"
    prospectus = "/Prospectus-v3.pdf"

[[params.dates]]
    date = "April 09, 2019"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "April 30, 2019"
    text = "Tickets go on Sale"
    done = true

[[params.dates]]
    date = "June 10, 2019"
    text = "CFP Closed"
    done = true

[[params.dates]]
    date = "July 22, 2019"
    text = "Schedule Announcement"
    done = true
    
[params.venue]
    name = "Melbourne Museum"
    link = "https://museumsvictoria.com.au/melbournemuseum/"
    map = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12609.740989119078!2d144.9717408!3d-37.803273!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8f2c10c1546cc221!2sMelbourne+Museum!5e0!3m2!1sen!2sau!4v1554896925628!5m2!1sen!2sau"
    text = "The venue is Melbourne Meuseum, it is a natural and cultural history museum located in the Carlton Gardens in Melbourne, Australia. Located adjacent to the Royal Exhibition Building, it is the largest museum in the Southern Hemisphere."

[params.tickets]
    price = "$60"
    diversityLink = "https://diversitytickets.org/en/events/435/"

[params.tickets.eventBrite]
    eventid = "55648142091"
    link = "https://www.eventbrite.com/e/serverlessdays-amsterdam-2019-tickets-55648142091"

[[params.sponsors.headline]]
    name = "AWS"
    link = "https://aws.amazon.com/"
    logo = "/images/sponsors/AWS.png"
    width = 200

[[params.sponsors.headline]]
    name = "Microsoft Azure"
    link = "https://azure.microsoft.com/en-au/free/"
    logo = "images/sponsors/Azure.png"
    width = 420 

[[params.sponsors.gold]]
    name = "Apptio Cloudability"
    link = "https://www.cloudability.com/"
    logo = "images/sponsors/Apptio_Cloudability_Logo_lowres.png"
    width = 200

[[params.sponsors.gold]]
    name = "IBM"
    link = "https://www.ibm.com/"
    logo = "images/sponsors/IBM_logoRR_blue60_RGB.gif"
    width = 200

[[params.sponsors.gold]]
    name = "Servian"
    link = "https://www.servian.com/"
    logo = "images/sponsors/servian.png"
    width = 200

[[params.sponsors.silver]]
    name = "MongoDB"
    link = "https://www.mongodb.com/"
    logo = "images/sponsors/MongoDB.jpg"
    width = 200

[[params.sponsors.community]]
    name = "Twilio"
    link = "https://www.twilio.com/"
    logo = "images/sponsors/twilio-logo-red.png"
    width = 200

[[params.sponsors.community]]
    name = "Just Digital People"
    link = "https://www.justdigitalpeople.com.au/"
    logo = "images/sponsors/justdigitalpeople.jpg"
    width = 200

[[params.agenda]]
    time = "8:00 - 9:00"
    type = "coffee"
    title = "Registration"
[[params.agenda]]
    time = "9:00 - 9:15"
    type = "coffee"
    title = "Opening Remarks"
[[params.agenda]]
    time = "9:15 - 9:50"
    type = "keynote"
    talk = "jeff-hollan"
[[params.agenda]]
    time = "9:50 - 10:25"
    type = "talk"
    talk = "jessica-flanagan"
[[params.agenda]]
    time = "10:25 - 10:45"
    type = "lightning"
    talk = "TBA"
[[params.agenda]]
    time = "10:45 - 11:00"
    type = "lightning"
    talk = "toshinori-sugita"
[[params.agenda]]
    time = "11:00 - 11:15"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "11:20 - 11:55"
    type = "talk"
    talk = "nelly-sattari"
[[params.agenda]]
    time = "11:55 - 12:30"
    type = "talk"
    talk = "scott-coulton"
[[params.agenda]]
    time = "12:30 - 12:50"
    type = "lightning"
    talk = "effy-elden"
[[params.agenda]]
    time = "12:50 - 13:05"
    type = "lightning"
    talk = "tariq-younas"
[[params.agenda]]
    time = "13:05 - 14:05"
    type = "lunch"
    title = "Lunch & Networking"
[[params.agenda]]
    time = "14:05 - 14:40"
    type = "talk"
    talk = "bret-mcgowan"
[[params.agenda]]
    time = "14:40 - 15:15"
    type = "talk"
    talk = "aditi-phadke"
[[params.agenda]]
    time = "15:15 - 15:50"
    type = "talk"
    talk = "aaron-powell"
[[params.agenda]]
    time = "15:50 - 16:10"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "16:10 - 16:40"
    type = "talk"
    talk = "pratik-khasnabis"
[[params.agenda]]
    time = "16:40 - 17:10"
    type = "talk"
    talk = "sam-chalela"
[[params.agenda]]
    time = "17:10 - 17:40"
    type = "keynote"
    talk = "danilo-poccia"
[[params.agenda]]
    time = "17:40 - 17:50"
    type = "coffee"
    title = "Closing remarks"
[[params.agenda]]
    time = "18:00 - open end"
    type = "afterparty"
    talk = "afterparty"
    description = "Afterparty at Queensberry Hotel"
